/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as ArchesRouteImport } from './routes/arches'
import { Route as CourtRouteImport } from './routes/court'
import { Route as CustomsRouteImport } from './routes/customs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GamesRouteImport } from './routes/games'
import { Route as HeelsRouteImport } from './routes/heels'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as PremadeRouteImport } from './routes/premade'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as SizeSevenRouteImport } from './routes/size-seven'
import { Route as SolesRouteImport } from './routes/soles'
import { Route as TheQueenRouteImport } from './routes/the-queen'
import { Route as TheThroneRouteImport } from './routes/the-throne'
import { Route as TherapyRouteImport } from './routes/therapy'
import { Route as ToesRouteImport } from './routes/toes'
import { Route as TributeRouteImport } from './routes/tribute'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as SessionsAudioRouteImport } from './routes/sessions.audio'
import { Route as SessionsChatRouteImport } from './routes/sessions.chat'
import { Route as SessionsVideoRouteImport } from './routes/sessions.video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchesRoute = ArchesRouteImport.update({
  id: '/arches',
  path: '/arches',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtRoute = CourtRouteImport.update({
  id: '/court',
  path: '/court',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomsRoute = CustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HeelsRoute = HeelsRouteImport.update({
  id: '/heels',
  path: '/heels',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const PremadeRoute = PremadeRouteImport.update({
  id: '/premade',
  path: '/premade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeSevenRoute = SizeSevenRouteImport.update({
  id: '/size-seven',
  path: '/size-seven',
  getParentRoute: () => rootRouteImport,
} as any)
const SolesRoute = SolesRouteImport.update({
  id: '/soles',
  path: '/soles',
  getParentRoute: () => rootRouteImport,
} as any)
const TheQueenRoute = TheQueenRouteImport.update({
  id: '/the-queen',
  path: '/the-queen',
  getParentRoute: () => rootRouteImport,
} as any)
const TheThroneRoute = TheThroneRouteImport.update({
  id: '/the-throne',
  path: '/the-throne',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapyRoute = TherapyRouteImport.update({
  id: '/therapy',
  path: '/therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ToesRoute = ToesRouteImport.update({
  id: '/toes',
  path: '/toes',
  getParentRoute: () => rootRouteImport,
} as any)
const TributeRoute = TributeRouteImport.update({
  id: '/tribute',
  path: '/tribute',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const SessionsAudioRoute = SessionsAudioRouteImport.update({
  id: '/sessions/audio',
  path: '/sessions/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsChatRoute = SessionsChatRouteImport.update({
  id: '/sessions/chat',
  path: '/sessions/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsVideoRoute = SessionsVideoRouteImport.update({
  id: '/sessions/video',
  path: '/sessions/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/arches': typeof ArchesRoute
  '/court': typeof CourtRoute
  '/customs': typeof CustomsRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/heels': typeof HeelsRoute
  '/journal': typeof JournalRouteWithChildren
  '/menu': typeof MenuRoute
  '/motion': typeof MotionRoute
  '/premade': typeof PremadeRoute
  '/protocol': typeof ProtocolRoute
  '/size-seven': typeof SizeSevenRoute
  '/soles': typeof SolesRoute
  '/the-queen': typeof TheQueenRoute
  '/the-throne': typeof TheThroneRoute
  '/therapy': typeof TherapyRoute
  '/toes': typeof ToesRoute
  '/tribute': typeof TributeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/sessions/audio': typeof SessionsAudioRoute
  '/sessions/chat': typeof SessionsChatRoute
  '/sessions/video': typeof SessionsVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/arches': typeof ArchesRoute
  '/court': typeof CourtRoute
  '/customs': typeof CustomsRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/heels': typeof HeelsRoute
  '/journal': typeof JournalRouteWithChildren
  '/menu': typeof MenuRoute
  '/motion': typeof MotionRoute
  '/premade': typeof PremadeRoute
  '/protocol': typeof ProtocolRoute
  '/size-seven': typeof SizeSevenRoute
  '/soles': typeof SolesRoute
  '/the-queen': typeof TheQueenRoute
  '/the-throne': typeof TheThroneRoute
  '/therapy': typeof TherapyRoute
  '/toes': typeof ToesRoute
  '/tribute': typeof TributeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/sessions/audio': typeof SessionsAudioRoute
  '/sessions/chat': typeof SessionsChatRoute
  '/sessions/video': typeof SessionsVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/arches': typeof ArchesRoute
  '/court': typeof CourtRoute
  '/customs': typeof CustomsRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/heels': typeof HeelsRoute
  '/journal': typeof JournalRouteWithChildren
  '/menu': typeof MenuRoute
  '/motion': typeof MotionRoute
  '/premade': typeof PremadeRoute
  '/protocol': typeof ProtocolRoute
  '/size-seven': typeof SizeSevenRoute
  '/soles': typeof SolesRoute
  '/the-queen': typeof TheQueenRoute
  '/the-throne': typeof TheThroneRoute
  '/therapy': typeof TherapyRoute
  '/toes': typeof ToesRoute
  '/tribute': typeof TributeRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/sessions/audio': typeof SessionsAudioRoute
  '/sessions/chat': typeof SessionsChatRoute
  '/sessions/video': typeof SessionsVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approach'
    | '/arches'
    | '/court'
    | '/customs'
    | '/faq'
    | '/games'
    | '/heels'
    | '/journal'
    | '/menu'
    | '/motion'
    | '/premade'
    | '/protocol'
    | '/size-seven'
    | '/soles'
    | '/the-queen'
    | '/the-throne'
    | '/therapy'
    | '/toes'
    | '/tribute'
    | '/journal/$slug'
    | '/sessions/audio'
    | '/sessions/chat'
    | '/sessions/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approach'
    | '/arches'
    | '/court'
    | '/customs'
    | '/faq'
    | '/games'
    | '/heels'
    | '/journal'
    | '/menu'
    | '/motion'
    | '/premade'
    | '/protocol'
    | '/size-seven'
    | '/soles'
    | '/the-queen'
    | '/the-throne'
    | '/therapy'
    | '/toes'
    | '/tribute'
    | '/journal/$slug'
    | '/sessions/audio'
    | '/sessions/chat'
    | '/sessions/video'
  id:
    | '__root__'
    | '/'
    | '/approach'
    | '/arches'
    | '/court'
    | '/customs'
    | '/faq'
    | '/games'
    | '/heels'
    | '/journal'
    | '/menu'
    | '/motion'
    | '/premade'
    | '/protocol'
    | '/size-seven'
    | '/soles'
    | '/the-queen'
    | '/the-throne'
    | '/therapy'
    | '/toes'
    | '/tribute'
    | '/journal/$slug'
    | '/sessions/audio'
    | '/sessions/chat'
    | '/sessions/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproachRoute: typeof ApproachRoute
  ArchesRoute: typeof ArchesRoute
  CourtRoute: typeof CourtRoute
  CustomsRoute: typeof CustomsRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRoute
  HeelsRoute: typeof HeelsRoute
  JournalRoute: typeof JournalRouteWithChildren
  MenuRoute: typeof MenuRoute
  MotionRoute: typeof MotionRoute
  PremadeRoute: typeof PremadeRoute
  ProtocolRoute: typeof ProtocolRoute
  SizeSevenRoute: typeof SizeSevenRoute
  SolesRoute: typeof SolesRoute
  TheQueenRoute: typeof TheQueenRoute
  TheThroneRoute: typeof TheThroneRoute
  TherapyRoute: typeof TherapyRoute
  ToesRoute: typeof ToesRoute
  TributeRoute: typeof TributeRoute
  SessionsAudioRoute: typeof SessionsAudioRoute
  SessionsChatRoute: typeof SessionsChatRoute
  SessionsVideoRoute: typeof SessionsVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arches': {
      id: '/arches'
      path: '/arches'
      fullPath: '/arches'
      preLoaderRoute: typeof ArchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/court': {
      id: '/court'
      path: '/court'
      fullPath: '/court'
      preLoaderRoute: typeof CourtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customs': {
      id: '/customs'
      path: '/customs'
      fullPath: '/customs'
      preLoaderRoute: typeof CustomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heels': {
      id: '/heels'
      path: '/heels'
      fullPath: '/heels'
      preLoaderRoute: typeof HeelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premade': {
      id: '/premade'
      path: '/premade'
      fullPath: '/premade'
      preLoaderRoute: typeof PremadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-seven': {
      id: '/size-seven'
      path: '/size-seven'
      fullPath: '/size-seven'
      preLoaderRoute: typeof SizeSevenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soles': {
      id: '/soles'
      path: '/soles'
      fullPath: '/soles'
      preLoaderRoute: typeof SolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-queen': {
      id: '/the-queen'
      path: '/the-queen'
      fullPath: '/the-queen'
      preLoaderRoute: typeof TheQueenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-throne': {
      id: '/the-throne'
      path: '/the-throne'
      fullPath: '/the-throne'
      preLoaderRoute: typeof TheThroneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapy': {
      id: '/therapy'
      path: '/therapy'
      fullPath: '/therapy'
      preLoaderRoute: typeof TherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toes': {
      id: '/toes'
      path: '/toes'
      fullPath: '/toes'
      preLoaderRoute: typeof ToesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribute': {
      id: '/tribute'
      path: '/tribute'
      fullPath: '/tribute'
      preLoaderRoute: typeof TributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/sessions/audio': {
      id: '/sessions/audio'
      path: '/sessions/audio'
      fullPath: '/sessions/audio'
      preLoaderRoute: typeof SessionsAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/chat': {
      id: '/sessions/chat'
      path: '/sessions/chat'
      fullPath: '/sessions/chat'
      preLoaderRoute: typeof SessionsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/video': {
      id: '/sessions/video'
      path: '/sessions/video'
      fullPath: '/sessions/video'
      preLoaderRoute: typeof SessionsVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproachRoute: ApproachRoute,
  ArchesRoute: ArchesRoute,
  CourtRoute: CourtRoute,
  CustomsRoute: CustomsRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRoute,
  HeelsRoute: HeelsRoute,
  JournalRoute: JournalRouteWithChildren,
  MenuRoute: MenuRoute,
  MotionRoute: MotionRoute,
  PremadeRoute: PremadeRoute,
  ProtocolRoute: ProtocolRoute,
  SizeSevenRoute: SizeSevenRoute,
  SolesRoute: SolesRoute,
  TheQueenRoute: TheQueenRoute,
  TheThroneRoute: TheThroneRoute,
  TherapyRoute: TherapyRoute,
  ToesRoute: ToesRoute,
  TributeRoute: TributeRoute,
  SessionsAudioRoute: SessionsAudioRoute,
  SessionsChatRoute: SessionsChatRoute,
  SessionsVideoRoute: SessionsVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
